//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package br.ufba.hupes.hospitaladmissionforram;

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import br.ufba.hupes.hospitaladmissionforram.connection.RestConnection_;
import br.ufba.hupes.hospitaladmissionforram.model.UserHolder_;
import org.androidannotations.api.BackgroundExecutor;

public final class MainService_
    extends MainService
{


    public static MainService_.IntentBuilder_ intent(Context context) {
        return new MainService_.IntentBuilder_(context);
    }

    public static MainService_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new MainService_.IntentBuilder_(fragment);
    }

    public static MainService_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new MainService_.IntentBuilder_(supportFragment);
    }

    private void init_() {
        userHolder = new UserHolder_(this);
        connection = new RestConnection_();
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

    @Override
    public void getHospitalsOnline() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainService_.super.getHospitalsOnline();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void sendResearches() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainService_.super.sendResearches();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void login() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainService_.super.login();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MainService_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MainService_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MainService_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MainService_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public ComponentName start() {
            return context_.startService(intent_);
        }

        public boolean stop() {
            return context_.stopService(intent_);
        }

    }

}
