//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package br.ufba.hupes.hospitaladmissionforram.model;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import org.androidannotations.api.sharedpreferences.BooleanPrefField;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class UserHolder_
    extends SharedPreferencesHelper
{

    private Context context_;

    public UserHolder_(Context context) {
        super(context.getSharedPreferences("UserHolder", 0));
        this.context_ = context;
    }

    public UserHolder_.UserHolderEditor_ edit() {
        return new UserHolder_.UserHolderEditor_(getSharedPreferences());
    }

    public BooleanPrefField admin() {
        return booleanField("admin", false);
    }

    public StringPrefField id() {
        return stringField("id", "");
    }

    public final static class UserHolderEditor_
        extends EditorHelper<UserHolder_.UserHolderEditor_>
    {


        UserHolderEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public BooleanPrefEditorField<UserHolder_.UserHolderEditor_> admin() {
            return booleanField("admin");
        }

        public StringPrefEditorField<UserHolder_.UserHolderEditor_> id() {
            return stringField("id");
        }

    }

}
