//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package br.ufba.hupes.hospitaladmissionforram.connection;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class RequestInterceptor_
    extends RequestInterceptor
{

    private Context context_;
    private static RequestInterceptor_ instance_;

    private RequestInterceptor_(Context context) {
        context_ = context;
    }

    public static RequestInterceptor_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new RequestInterceptor_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
        context = context_;
    }

}
